@BASE_URL=http://localhost:3001
# @BASE_URL=

### Get all blogs
GET {{BASE_URL}}/api/blogs

### Get all users
GET {{BASE_URL}}/api/users

### Create new user
POST {{BASE_URL}}/api/users
Content-Type: application/json

# {
#   "username": "lePaul",
#   "name": "Paul Serban",
#   "password": "supersecretpassword"
# }

# {
#   "username": "jDoe",
#   "name": "John Doe",
#   "password": "supersecretpassword"
# }

{
  "username": "janeD",
  "name": "Jane Doe",
  "password": "supersecretpassword"
}

### Login user
# @name login
POST {{BASE_URL}}/api/login
Content-Type: application/json

{
  "username": "lePaul",
  "password": "supersecretpassword"
}

### Create new post
POST {{BASE_URL}}/api/blogs
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

# {
#   "title":"Few-Shot Prompt Libraries: How to Build Reusable Examples that Don’t Rot",
#   "author":"Paul Serban",
#   "url":"https://paulserban.eu/blog/post/few-shot-prompt-libraries-how-to-build-reusable-examples-that-dont-rot/",
#   "likes": 0
# }

# {
#   "title":"3 Meta-Prompting Patterns for Enterprise-Grade Structured Outputs",
#   "author":"Paul Serban",
#   "url":"https://paulserban.eu/blog/post/3-meta-prompting-patterns-for-enterprise-grade-structured-outputs/",
#   "likes": 0
# }

# {
#   "title":"Applying SOLID to prompt engineering: why your prompts violate the single responsibility principle",
#   "author":"Paul Serban",
#   "url":"https://paulserban.eu/blog/post/applying-solid-to-prompt-engineering-why-your-prompts-violate-the-single-responsibility-principle/",
#   "likes": 0
# }

# {
#   "title":"Chain-of-Validation: Engineering Reliable AI Systems Through Iterative Self-Verification",
#   "author":"Paul Serban",
#   "url":"https://paulserban.eu/blog/post/chain-of-validation-engineering-reliable-ai-systems-through-iterative-self-verification/",
#   "likes": 0
# }

{
  "title": "TDD Harms Architecture",
  "author": "Robert C. Martin AKA Uncle Bob",
  "url": "https://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
  "likes": 0
}

### Delete a post
DELETE {{BASE_URL}}/api/blogs/6a0c8136eb8f98b3f6830f55
Authorization: Bearer {{login.response.body.token}}

### Update a post
PUT {{BASE_URL}}/api/blogs/6a0cd1f4ae74413afc9e98dd
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "title": "TDD Harms Architecture - Updated",
  "author": "Robert C. Martin AKA Uncle Bob",
  "url": "https://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
  "likes": 10
}