@BASE_URL=http://localhost:3001
# @BASE_URL=https://phonebook-backend-fso-2026-part3.onrender.com

### Get all persons
GET {{BASE_URL}}/api/persons

### Get single person (existing)
GET {{BASE_URL}}/api/persons/6a08cba445804f3f575b02a0

### Get single person (non-existent)
GET {{BASE_URL}}/api/persons/6a08cba445804f3f575b02a1

### Get info page
GET {{BASE_URL}}/info

### Create new person - SUCCESS
POST {{BASE_URL}}/api/persons
Content-Type: application/json

{
  "name": "Papa John",
  "number": "040-123456"
}

### Create new person - MISSING FIELD
POST {{BASE_URL}}/api/persons
Content-Type: application/json

{
  "name": "Jane Smith"
}

### Create new person - DUPLICATE NAME
POST {{BASE_URL}}/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "999-999-9999"
}

### Delete existing person
DELETE {{BASE_URL}}/api/persons/6a08cb5845804f3f575b029c

### Delete non-existent person
DELETE {{BASE_URL}}/api/persons/99
